services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 25575
      MEMORY: 6G
      TYPE: FABRIC
      MAX_PLAYERS: 2
      SERVER_NAME: ${SERVER_NAME}
      MOTD: ${MOTD}"Join for extra sauce"
      ICON: ${ICON_URL}
      MODRINTH_PROJECTS: |
        ${MODRINTH_MODS}
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      CF_API_KEY: ${CF_API_KEY}
      CURSEFORGE_FILES: |
        ${CURSEFORGE_MODS}
    volumes:
      - /mnt/data:/data
    restart: unless-stopped